# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'perceptron_multi_class_rem.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1010, 554)
        MainWindow.setMaximumSize(QtCore.QSize(1100, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.file__h_layout = QtWidgets.QHBoxLayout()
        self.file__h_layout.setObjectName("file__h_layout")
        self.file_label = QtWidgets.QLabel(self.centralwidget)
        self.file_label.setObjectName("file_label")
        self.file__h_layout.addWidget(self.file_label)
        self.file_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.file_inp.setObjectName("file_inp")
        self.file__h_layout.addWidget(self.file_inp)
        self.load_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_file_button.setObjectName("load_file_button")
        self.file__h_layout.addWidget(self.load_file_button)
        self.select_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.select_file_button.setObjectName("select_file_button")
        self.file__h_layout.addWidget(self.select_file_button)
        self.verticalLayout.addLayout(self.file__h_layout)
        self.main_content_h_layout = QtWidgets.QHBoxLayout()
        self.main_content_h_layout.setObjectName("main_content_h_layout")
        self.graph_h_layout = QtWidgets.QHBoxLayout()
        self.graph_h_layout.setObjectName("graph_h_layout")
        self.graph_w = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_w.sizePolicy().hasHeightForWidth())
        self.graph_w.setSizePolicy(sizePolicy)
        self.graph_w.setMinimumSize(QtCore.QSize(500, 500))
        self.graph_w.setObjectName("graph_w")
        self.graph_h_layout.addWidget(self.graph_w)
        self.main_content_h_layout.addLayout(self.graph_h_layout)
        self.state_v_layout = QtWidgets.QVBoxLayout()
        self.state_v_layout.setObjectName("state_v_layout")
        self.state_out_widg = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state_out_widg.sizePolicy().hasHeightForWidth())
        self.state_out_widg.setSizePolicy(sizePolicy)
        self.state_out_widg.setObjectName("state_out_widg")
        self.state_v_layout.addWidget(self.state_out_widg)
        self.control_h_layout = QtWidgets.QHBoxLayout()
        self.control_h_layout.setObjectName("control_h_layout")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_button.sizePolicy().hasHeightForWidth())
        self.start_button.setSizePolicy(sizePolicy)
        self.start_button.setObjectName("start_button")
        self.control_h_layout.addWidget(self.start_button)
        self.state_input_v_layout = QtWidgets.QVBoxLayout()
        self.state_input_v_layout.setObjectName("state_input_v_layout")
        self.rand_weights_h_layout = QtWidgets.QHBoxLayout()
        self.rand_weights_h_layout.setObjectName("rand_weights_h_layout")
        self.rand_weights_label = QtWidgets.QLabel(self.centralwidget)
        self.rand_weights_label.setObjectName("rand_weights_label")
        self.rand_weights_h_layout.addWidget(self.rand_weights_label)
        self.rand_weights_check_b = QtWidgets.QCheckBox(self.centralwidget)
        self.rand_weights_check_b.setText("")
        self.rand_weights_check_b.setChecked(True)
        self.rand_weights_check_b.setObjectName("rand_weights_check_b")
        self.rand_weights_h_layout.addWidget(self.rand_weights_check_b)
        self.state_input_v_layout.addLayout(self.rand_weights_h_layout)
        self.max_inp_h_layout = QtWidgets.QHBoxLayout()
        self.max_inp_h_layout.setObjectName("max_inp_h_layout")
        self.max_txt_v_layout = QtWidgets.QVBoxLayout()
        self.max_txt_v_layout.setObjectName("max_txt_v_layout")
        self.max_epochs_label = QtWidgets.QLabel(self.centralwidget)
        self.max_epochs_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.max_epochs_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.max_epochs_label.setObjectName("max_epochs_label")
        self.max_txt_v_layout.addWidget(self.max_epochs_label)
        self.batch_size_label = QtWidgets.QLabel(self.centralwidget)
        self.batch_size_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.batch_size_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.batch_size_label.setObjectName("batch_size_label")
        self.max_txt_v_layout.addWidget(self.batch_size_label)
        self.max_inp_h_layout.addLayout(self.max_txt_v_layout)
        self.max_input_v_layout = QtWidgets.QVBoxLayout()
        self.max_input_v_layout.setObjectName("max_input_v_layout")
        self.max_epoch_inp = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_epoch_inp.sizePolicy().hasHeightForWidth())
        self.max_epoch_inp.setSizePolicy(sizePolicy)
        self.max_epoch_inp.setMinimumSize(QtCore.QSize(50, 0))
        self.max_epoch_inp.setObjectName("max_epoch_inp")
        self.max_input_v_layout.addWidget(self.max_epoch_inp)
        self.batch_size_inp = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batch_size_inp.sizePolicy().hasHeightForWidth())
        self.batch_size_inp.setSizePolicy(sizePolicy)
        self.batch_size_inp.setMinimumSize(QtCore.QSize(50, 0))
        self.batch_size_inp.setObjectName("batch_size_inp")
        self.max_input_v_layout.addWidget(self.batch_size_inp)
        self.max_inp_h_layout.addLayout(self.max_input_v_layout)
        self.state_input_v_layout.addLayout(self.max_inp_h_layout)
        self.control_h_layout.addLayout(self.state_input_v_layout)
        self.state_info_h_layout = QtWidgets.QHBoxLayout()
        self.state_info_h_layout.setObjectName("state_info_h_layout")
        self.state_txt_v_layout = QtWidgets.QVBoxLayout()
        self.state_txt_v_layout.setObjectName("state_txt_v_layout")
        self.learn_rate_label = QtWidgets.QLabel(self.centralwidget)
        self.learn_rate_label.setObjectName("learn_rate_label")
        self.state_txt_v_layout.addWidget(self.learn_rate_label)
        self.loss_label = QtWidgets.QLabel(self.centralwidget)
        self.loss_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loss_label.setObjectName("loss_label")
        self.state_txt_v_layout.addWidget(self.loss_label)
        self.accuracy_label = QtWidgets.QLabel(self.centralwidget)
        self.accuracy_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.accuracy_label.setObjectName("accuracy_label")
        self.state_txt_v_layout.addWidget(self.accuracy_label)
        self.state_info_h_layout.addLayout(self.state_txt_v_layout)
        self.state_out_v_layout = QtWidgets.QVBoxLayout()
        self.state_out_v_layout.setObjectName("state_out_v_layout")
        self.learn_rate_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.learn_rate_inp.setObjectName("learn_rate_inp")
        self.state_out_v_layout.addWidget(self.learn_rate_inp)
        self.loss_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.loss_inp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loss_inp.sizePolicy().hasHeightForWidth())
        self.loss_inp.setSizePolicy(sizePolicy)
        self.loss_inp.setMinimumSize(QtCore.QSize(50, 0))
        self.loss_inp.setObjectName("loss_inp")
        self.state_out_v_layout.addWidget(self.loss_inp)
        self.accuracy_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.accuracy_inp.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accuracy_inp.sizePolicy().hasHeightForWidth())
        self.accuracy_inp.setSizePolicy(sizePolicy)
        self.accuracy_inp.setMinimumSize(QtCore.QSize(50, 0))
        self.accuracy_inp.setObjectName("accuracy_inp")
        self.state_out_v_layout.addWidget(self.accuracy_inp)
        self.state_info_h_layout.addLayout(self.state_out_v_layout)
        self.control_h_layout.addLayout(self.state_info_h_layout)
        self.state_v_layout.addLayout(self.control_h_layout)
        self.main_content_h_layout.addLayout(self.state_v_layout)
        self.verticalLayout.addLayout(self.main_content_h_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Perceptron multi classifier"))
        self.file_label.setText(_translate("MainWindow", "File:"))
        self.load_file_button.setText(_translate("MainWindow", "Load"))
        self.select_file_button.setText(_translate("MainWindow", "Select"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.rand_weights_label.setText(_translate("MainWindow", "Random initialization of weights"))
        self.max_epochs_label.setText(_translate("MainWindow", "Maximum number of epochs:"))
        self.batch_size_label.setText(_translate("MainWindow", "Batch size:"))
        self.learn_rate_label.setText(_translate("MainWindow", "Learning rate:"))
        self.loss_label.setText(_translate("MainWindow", "Loss:"))
        self.accuracy_label.setText(_translate("MainWindow", "Accuracy:"))
